rules:
  end-of-file:
    enable: true
    ignore:
      - extractor/filesystem/os/dpkg/testdata/dpkg/trailingnewlines
      - extractor/filesystem/os/dpkg/testdata/opkg/trailingnewlines
      - extractor/filesystem/language/julia/manifesttoml/testdata/no-dependency.toml
      - extractor/filesystem/language/julia/projecttoml/testdata/not-toml.txt
      - extractor/filesystem/language/julia/manifesttoml/testdata/no-dependency.toml
      - extractor/filesystem/language/julia/projecttoml/testdata/project.toml
